name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run isort
        uses: isort/isort-action@v1
      - name: Run black
        uses: psf/black@stable